### ISSUE TITLE
Is there any way to add filter for any number in this plugin like calllog?

### ISSUE THREAD

**Issue by UmeshRajani** [creacore-team/cordova-plugin-smslog#2]
We have only this option in this plugin, do we add like expression type, which filter operator already available in calllog plugin (https://github.com/creacore-team/cordova-plugin-calllog)
let filters = [{
    "name": "address",
    "value": "+32477000000",
    "operator": "==",
},
{
    "name": "date",
    "value": 1517266800000,
    "operator": ">="
}];

And can we get full sms body instead of just meta data? Is there any way I can build and add in my cordova project? I

I'm new in cordova so not sure what should be done here. 
Thank you.

**Comment by Bruno361** [comment]
In this version, these are the only filters that are available. We are planning to add some more in the next versions, but I cannot tell you exactly when these will be released, yet.

As for the full sms body, it is not available, because the scope of this plugin concerns the logs and not the sms content. You should easily find some other plugins that allow you to access the sms body, though.
